server:
  port: 1111
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: testowatestowe83@gmail.com
    password: yyqplkoyyythncrp
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  profiles:
    active: loadInitialData
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true